Repository MeditationDuck/covid19, pull requests merged in 2021-04, with the labels that each got.

#1475 check_broken_linkで拒否られる場合があるっぽいのでUserAgentを追加
  spec/feature/check_broken_links_spec.rb
  spec/lib/SiteTopUpper.rb
Labels: 岩手独自機能

#1476 staging <= development
  data/alert.json
  data/daily_positive_detail.json
  data/data.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  spec/feature/check_broken_links_spec.rb
  spec/lib/SiteTopUpper.rb
Labels: to_staging

#1480 検査陽性者の状況に前日との差 ± を表示する 実装
  .github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml
  .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
  .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
  assets/locales/en.json
  assets/locales/ja.json
  components/ConfirmedCasesDetailsTable.vue
  components/cards/ConfirmedCasesDetailsCard.vue
  data/data.json
  data/main_summary.json
  spec/lib/ConfirmedCasesDetailsCard.rb
  spec/spec_helper.rb
  utils/formatConfirmedCases.ts
Labels: 岩手独自機能

#1481 staging <= development
  .github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml
  .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
  .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
  assets/locales/en.json
  assets/locales/ja.json
  components/ConfirmedCasesDetailsTable.vue
  components/cards/ConfirmedCasesDetailsCard.vue
  data/alert.json
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  spec/lib/ConfirmedCasesDetailsCard.rb
  spec/spec_helper.rb
  utils/formatConfirmedCases.ts
  yarn.lock
Labels: to_staging

#1482 master <= staging
  .github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml
  .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
  .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
  assets/locales/en.json
  assets/locales/ja.json
  components/ConfirmedCasesDetailsTable.vue
  components/cards/ConfirmedCasesDetailsCard.vue
  data/data.json
  data/main_summary.json
  package.json
  spec/lib/ConfirmedCasesDetailsCard.rb
  spec/spec_helper.rb
  utils/formatConfirmedCases.ts
  yarn.lock
Labels: to_master

#1483 fix: layout no-wrap
  components/ConfirmedCasesDetailsTable.vue
Labels: 岩手独自機能

#1484 staging <= development
  components/ConfirmedCasesDetailsTable.vue
  data/alert.json
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
Labels: to_staging

#1487 add self_disclosure_form
  components/WhatsNew.vue
  components/cards/SelfDisclosuresCard.vue
  spec/lib/SelfDisclosuresCard.rb
Labels: 岩手独自機能

#1488 staging <= development
  components/WhatsNew.vue
  components/cards/SelfDisclosuresCard.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  spec/lib/SelfDisclosuresCard.rb
Labels: to_staging

#1490 DetailsCardの前日差 spec
  spec/lib/ConfirmedCasesDetailsCard.rb
Labels: 岩手独自機能

#1491 staging <= development
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  spec/lib/ConfirmedCasesDetailsCard.rb
Labels: to_staging

#1498 staging <= development
  .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
  .github/workflows/on_pr_from_renovate_rspec.yml
  .github/workflows/on_pr_to_dev_rspec.yml
  .github/workflows/on_push_to_dev_rspec.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  data/alert.json
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  yarn.lock
Labels: to_staging

#1499 master <= staging
  .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
  .github/workflows/on_pr_from_renovate_rspec.yml
  .github/workflows/on_pr_to_dev_rspec.yml
  .github/workflows/on_push_to_dev_rspec.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: to_master

#1504 staging <= development
  .github/workflows/on_dispatch_from_googleSheetsMenuWithoutOGP_master.yml
  .github/workflows/on_dispatch_from_googleSheetsMenu_development.yml
  .github/workflows/on_dispatch_from_googleSheetsMenu_master.yml
  .github/workflows/on_pr_from_renovate_rspec.yml
  .github/workflows/on_pr_to_dev_reviewdog.yml
  .github/workflows/on_pr_to_dev_rspec.yml
  .github/workflows/on_pr_to_stage_audit-staging.yml
  .github/workflows/on_push_to_dev_rspec.yml
  .github/workflows/on_push_to_stage_staging.yml
  .node-version
  .nvmrc
  Dockerfile
  FOR_DEVELOPERS.md
  data/alert.json
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/news.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  docs/en/FOR_DEVELOPERS.md
  package.json
Labels: to_staging

#1508 ConfirmedCasesAttributesCard に接触歴の有無を表示する
  assets/locales/en.json
  assets/locales/ja.json
  components/DataTable.vue
  components/cards/ConfirmedCasesAttributesCard.vue
  spec/lib/ConfirmedCasesAttributesCard.rb
  utils/formatTable.ts
Labels: 岩手独自機能

#1509 staging <= development
  assets/locales/en.json
  assets/locales/ja.json
  components/DataTable.vue
  components/cards/ConfirmedCasesAttributesCard.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  spec/lib/ConfirmedCasesAttributesCard.rb
  utils/formatTable.ts
  yarn.lock
Labels: to_staging

#1514 staging <= development
  data/alert.json
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  yarn.lock
Labels: to_staging

#1517 staging <= development
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  package.json
  yarn.lock
Labels: to_staging

#1521 staging <= development
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  yarn.lock
Labels: to_staging

#1524 hotfix: データが100を超えていたので暫定的に200に増やして表示切れ対処
  components/WhatsNew.vue
Labels: 岩手独自機能

#1525 staging <= development
  components/WhatsNew.vue
  data/alert.json
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
Labels: to_staging

#1530 staging <= development
  assets/locales/en.json
  assets/locales/ja.json
  data/alert.json
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/news.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  yarn.lock
Labels: to_staging

#1533 staging <= development
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  yarn.lock
Labels: to_staging

#1536 staging <= development
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  yarn.lock
Labels: to_staging

#1541 staging <= development
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  yarn.lock
Labels: to_staging

#1547 staging <= development
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  yarn.lock
Labels: to_staging

#1554 staging <= development
  .github/workflows/on_pr_to_stage_audit-staging.yml
  data/alert.json
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  yarn.lock
Labels: to_staging

#1560 直近1週間の陽性者数で市町村の地図を塗り分け
  components/CardsMonitoring.vue
  components/DataViewDataSetPanel.vue
  components/WeeklyMap.vue
  components/cards/WeeklyMapCard.vue
  nuxt.config.dev.ts
  nuxt.config.ts
  package.json
  pages/cards/_card.vue
  static/03_city.l.topo.json
  types/weekly-map.d.ts
  ui-test/ogp_screenshot.py
  yarn.lock
Labels: 岩手独自機能

#1561 staging <= development
  components/CardsMonitoring.vue
  components/DataViewDataSetPanel.vue
  components/WeeklyMap.vue
  components/cards/WeeklyMapCard.vue
  data/alert.json
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  nuxt.config.dev.ts
  nuxt.config.ts
  package.json
  pages/cards/_card.vue
  static/03_city.l.topo.json
  types/weekly-map.d.ts
  ui-test/ogp_screenshot.py
  yarn.lock
Labels: to_staging

#1564 staging <= development
  components/cards/WeeklyMapCard.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
Labels: to_staging

#1566 岩手県全域の場合は陽性件数を表示する
  components/WeeklyMap.vue
  components/cards/WeeklyMapCard.vue
Labels: 岩手独自機能

#1567 staging <= development
  components/WeeklyMap.vue
  components/cards/WeeklyMapCard.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  package.json
  yarn.lock
Labels: to_staging

#1571 weekly_mapで陽性数が0の場合は fff にする
  components/WeeklyMap.vue
Labels: 岩手独自機能

#1572 staging <= development
  components/WeeklyMap.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
Labels: to_staging

#1570 #1569 マウスオーバーで市町村のボーダーの色を999・太さ2pxに調整
  components/WeeklyMap.vue
Labels: 岩手独自機能

#1569 市町村ごとの感染状況を地図の塗り分けで表現: マウスオーバー時のスタイルを変更
  components/WeeklyMap.vue
Labels: 岩手独自機能

#1575 staging <= development
  components/WeeklyMap.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/news.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  yarn.lock
Labels: to_staging

#1577 Fix city map mouseover
  components/WeeklyMap.vue
  components/cards/WeeklyMapCard.vue
Labels: 岩手独自機能

#1578 staging <= development
  components/WeeklyMap.vue
  components/cards/WeeklyMapCard.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
Labels: to_staging

#1584 staging <= development
  components/SideNavigation.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  package.json
  spec/feature/index/index_SideNavigation_spec.rb
  yarn.lock
Labels: to_staging

#1587 入院と宿泊療養のグラフに「調整中」を追加
  assets/locales/en.json
  assets/locales/ja.json
  components/HospitalizedTimeStackedBarChart.vue
  components/cards/HospitalizedNumberCard.vue
  spec/feature/cards/cards_HospitalizedNumberCard_spec.rb
  spec/lib/HospitalizedNumberCard.rb
  utils/colors.ts
Labels: 岩手独自機能

#1588 staging <= development
  assets/locales/en.json
  assets/locales/ja.json
  components/HospitalizedTimeStackedBarChart.vue
  components/cards/HospitalizedNumberCard.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  spec/feature/cards/cards_HospitalizedNumberCard_spec.rb
  spec/lib/HospitalizedNumberCard.rb
  utils/colors.ts
Labels: to_staging

#1590 調整中の色を グレー に変更
  utils/colors.ts
Labels: 岩手独自機能

#1591 staging <= development
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  utils/colors.ts
Labels: to_staging

#1595 SideNavigationの文言をシンプルに変更
  assets/locales/en.json
  assets/locales/ja.json
Labels: 岩手独自機能

#1596 CapybaraのChrome起動オプションでGoogle Analyticsを明示的に迂回する
  spec/spec_helper.rb
Labels: 岩手独自機能

#1597 locales: 直近1週間の陽性例マップの英語化
  assets/locales/en.json
  assets/locales/ja.json
  components/DataViewDataSetPanel.vue
  components/WeeklyMap.vue
  components/cards/WeeklyMapCard.vue
  pages/cards/_card.vue
Labels: 岩手独自機能

#1598 staging <= development
  assets/locales/en.json
  assets/locales/ja.json
  components/DataViewDataSetPanel.vue
  components/WeeklyMap.vue
  components/cards/WeeklyMapCard.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  pages/cards/_card.vue
  spec/spec_helper.rb
Labels: to_staging

#1601 カーソルが市町村から離れたら岩手県全域のdatasetpanelを表示する
  components/WeeklyMap.vue
Labels: 岩手独自機能

#1604 staging <= development
  assets/locales/en.json
  assets/locales/ja.json
  components/MenuList.vue
  components/SideNavigation.vue
  components/WeeklyMap.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  package.json
  spec/feature/index/index_SideNavigation_spec.rb
  yarn.lock
Labels: to_staging

#1607 陽性患者数(市町村別) から「ふりがな」を非表示にする / Firefoxでのソートbugfix
  assets/locales/ja.json
  components/ConfirmedCasesByMunicipalitiesTable.vue
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
  spec/lib/ConfirmedCasesByMunicipalitiesCard.rb
Labels: 岩手独自機能

#1608 staging <= development
  assets/locales/ja.json
  components/ConfirmedCasesByMunicipalitiesTable.vue
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  data/self_disclosures.json
  spec/lib/ConfirmedCasesByMunicipalitiesCard.rb
Labels: to_staging

#1610 en の ruby 削除もれ fix / table > thead > tr > th に関する spec の追加
  assets/locales/en.json
  spec/lib/ConfirmedCasesByMunicipalitiesCard.rb
Labels: 岩手独自機能

#1611 staging <= development
  assets/locales/en.json
  data/daily_positive_detail.json
  data/data.json
  data/main_summary.json
  data/patient_municipalities.json
  data/positive_by_diagnosed.json
  data/positive_rate.json
  data/positive_status.json
  spec/lib/ConfirmedCasesByMunicipalitiesCard.rb
Labels: to_staging
